<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>XTest - <?php //echo $page->title ?></title>
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="/XPages/site/layouts/styles/main.css">
</head>
<body>

	<div class="header">

	  <div class="container">
	    <h1><?php echo $page->title ?></h1>
	  </div>
	</div>
